type: Move Container
desc: Move a container from one location to another using a robotic arm

device_types:
  - robot_arm

input_containers:
  beaker:
    type: beaker

input_parameters:
  target_location:
    type: str
    desc: The location to move the container to
