type: Score Color
desc: Score a color based on how close it is to an expected color

input_parameters:
  red:
    type: int
    unit: n/a
    min: 0
    max: 255
    desc: The red component of the color
  green:
    type: int
    unit: n/a
    min: 0
    max: 255
    desc: The green component of the color
  blue:
    type: int
    unit: n/a
    min: 0
    max: 255
    desc: The blue component of the color
  total_color_volume:
    type: float
    unit: mL
    min: 0
    desc: The total volume of the color in the container for which the RGB values were measured
  max_total_color_volume:
    type: float
    unit: mL
    min: 0
    desc: The maximum total volume of the color that can be in the container
  target_color:
    type: list
    element_type: int
    desc: The expected color

output_parameters:
  loss:
    type: float
    unit: n/a
    desc: Total loss of the color compared to the expected color
  color_distance:
    type: float
    unit: n/a
    desc: The distance between the color and the expected color
