type: Score Color
desc: Score a color based on how close it is to an expected color

input_parameters:
  red:
    type: int
    unit: n/a
    min: 0
    max: 255
    desc: The red component of the color
  green:
    type: int
    unit: n/a
    min: 0
    max: 255
    desc: The green component of the color
  blue:
    type: int
    unit: n/a
    min: 0
    max: 255
    desc: The blue component of the color
  target_color:
    type: list
    element_type: int
    length: 3
    desc: The expected RGB color

output_parameters:
  loss:
    type: float
    unit: n/a
    desc: Normalized color distance from the target color