type: Retrieve Container
desc: Retrieve a container from a container storage unit using a robotic arm

device_types:
  - robot_arm

input_containers:
  beaker:
    type: beaker

input_parameters:
  target_location:
    type: str
    desc: The location to move the container to

output_containers:
  beaker:
    type: beaker
