type: Clean Container
desc: Clean a container by rinsing it

device_types:
  - cleaning_station

input_containers:
  beaker:
    type: beaker

input_parameters:
  duration:
    type: int
    unit: sec
    desc: How long to clean
