type: Store Container
desc: Store a container at a container storage

devices:
  robot_arm:
    type: robot_arm

input_resources:
  beaker:
    type: beaker

input_parameters:
  storage_location:
    type: str
    desc: The location to store the container at
